In [14]:
import numpy as np

In [15]:
MATRIX_SIZE=(4,5,7)
matrix_A=np.random.rand(*MATRIX_SIZE)

In [16]:
print(f"A:{str(matrix_A)}")

A:[[[0.88576801 0.91542383 0.16895761 0.2644475  0.79297115 0.13337411
   0.95732126]
  [0.97383334 0.945572   0.90746442 0.03545413 0.80493543 0.49790563
   0.9067039 ]
  [0.59198859 0.64808995 0.79773082 0.06622276 0.11689567 0.04903448
   0.62182265]
  [0.34508505 0.0972048  0.49956957 0.08246241 0.89263507 0.88946626
   0.02857221]
  [0.12128907 0.27854648 0.64112224 0.83934224 0.11842432 0.29698713
   0.1828946 ]]

 [[0.02347686 0.83710456 0.99911289 0.47736883 0.06686749 0.37310206
   0.62218651]
  [0.03749243 0.7760045  0.03219153 0.95209835 0.50837183 0.52567089
   0.72462424]
  [0.27216265 0.72581192 0.56568856 0.13465707 0.04805902 0.67449045
   0.07693683]
  [0.40837342 0.00128874 0.41052687 0.7115363  0.10640304 0.99568036
   0.54683942]
  [0.22325531 0.40818093 0.05038154 0.95078275 0.27331797 0.64684198
   0.69587522]]

 [[0.24688001 0.02647357 0.32133381 0.24565924 0.13327576 0.91465587
   0.05238384]
  [0.01963075 0.38615338 0.65995588 0.44820269 0.60616455 0.06437396
 

In [17]:
mapper_for_B=lambda x: (x>=0.5)*1

def mapper_for_C(x):
    if x>=0.9: return 5 
    elif x>=0.7: return 4
    elif x>=0.5: return 3
    elif x>=0.3: return 2
    else: return 1

In [18]:
matrix_B=np.vectorize(mapper_for_B)(matrix_A)
matrix_C=np.vectorize(mapper_for_C)(matrix_A)

In [19]:
print(f"B:{str(matrix_B)}")

B:[[[1 1 0 0 1 0 1]
  [1 1 1 0 1 0 1]
  [1 1 1 0 0 0 1]
  [0 0 0 0 1 1 0]
  [0 0 1 1 0 0 0]]

 [[0 1 1 0 0 0 1]
  [0 1 0 1 1 1 1]
  [0 1 1 0 0 1 0]
  [0 0 0 1 0 1 1]
  [0 0 0 1 0 1 1]]

 [[0 0 0 0 0 1 0]
  [0 0 1 0 1 0 0]
  [0 1 0 1 1 1 0]
  [1 0 0 0 1 0 0]
  [0 1 1 0 1 1 0]]

 [[1 0 1 1 1 1 1]
  [1 0 0 0 0 1 0]
  [0 1 1 1 1 1 0]
  [0 0 0 0 0 1 1]
  [1 0 1 0 0 1 1]]]


In [20]:
print(f"C:{str(matrix_C)}")

C:[[[4 5 1 1 4 1 5]
  [5 5 5 1 4 2 5]
  [3 3 4 1 1 1 3]
  [2 1 2 1 4 4 1]
  [1 1 3 4 1 1 1]]

 [[1 4 5 2 1 2 3]
  [1 4 1 5 3 3 4]
  [1 4 3 1 1 3 1]
  [2 1 2 4 1 5 3]
  [1 2 1 5 1 3 3]]

 [[1 1 2 1 1 5 1]
  [1 2 3 2 3 1 1]
  [1 3 2 4 4 3 1]
  [4 1 2 2 4 1 2]
  [2 3 3 2 4 4 2]]

 [[4 1 4 4 4 3 3]
  [4 1 1 1 2 4 1]
  [2 4 4 4 4 4 1]
  [2 2 1 1 2 3 4]
  [4 2 4 1 2 5 5]]]


In [21]:
W1 = [0.2, 0.1, 0.2, 0.5]
W2 = [0.3, 0.1, 0.2, 0.1, 0.3]
W3 = [0.1, 0.2, 0.15, 0.15, 0.2, 0.1, 0.2]

def sum_by_coefs(array):
    sum = 0
    for i in range(4):
        for j in range(5):
            for k in range(7):
                sum += W1[i] * W2[j] * W3[k] * array[i][j][k]
    return sum

In [22]:
for array, name in zip([matrix_A,matrix_B,matrix_C],['A','B',"C"]):
    print(f'{name}: {sum_by_coefs(array)}')

A: 0.573183792999281
B: 0.5675000000000003
C: 2.9450000000000007


In [56]:
print(f'Element 221: |{matrix_A[1][1][0]:.10f}|{matrix_B[1][1][0]}|{matrix_C[1][1][0]}|')
print(f'Element 333: |{matrix_A[2][2][2]:.10f}|{matrix_B[2][2][2]}|{matrix_C[2][2][2]}|')
print(f'Element 422: |{matrix_A[3][1][1]:.10f}|{matrix_B[3][1][1]}|{matrix_C[3][1][1]}|')
print(f'Element 147: |{matrix_A[0][3][6]:.10f}|{matrix_B[0][3][6]}|{matrix_C[0][3][6]}|')
print(f'Element 323: |{matrix_A[2][1][2]:.10f}|{matrix_B[2][1][2]}|{matrix_C[2][1][2]}|')

Element 221: |0.0374924287|0|1|
Element 333: |0.4990132657|0|2|
Element 422: |0.1179995242|0|1|
Element 147: |0.0285722136|0|1|
Element 323: |0.6599558752|1|3|


In [65]:
def get_minimums(matrix, number):
    minimums=sorted(np.ravel(matrix))[:number]
    d={}
    get_index=lambda x: x[0]
    for i in minimums:
        d[i]=list(map(get_index,np.where(matrix==i)))
    return d

get_minimums(matrix_A,5)

{0.0012887447965609367: [1, 3, 1],
 0.019630751793577428: [2, 1, 0],
 0.023476862642737184: [1, 0, 0],
 0.02647356846202631: [2, 0, 1],
 0.028572213634764143: [0, 3, 6]}

In [64]:
def write_to_file(array, file_name, matrix_name):
    with open(file_name, mode="w") as file:
        file.write(f'Matrix {matrix_name}:\n {array}\n\n')
        file.write(f'Q={sum_by_coefs(array)}\n\n')
        file.write(f'Lowest values: {get_minimums(array,5)}')

write_to_file(matrix_A, "Matrix A.txt", "A")
write_to_file(matrix_B, "Matrix B.txt", "B")
write_to_file(matrix_C, "Matrix c.txt", "C")